import type { PolicyCheck, PolicyEvaluable } from './policy/types';
import { MandateService, mandateService as defaultMandates } from './policy/MandateService';
import { AllowlistService, allowlistService as defaultAllowlist } from './policy/AllowlistService';
import { SelectorRegistry } from './policy/SelectorRegistry';
import { CooldownService, cooldownService as defaultCooldown } from './policy/CooldownService';
import { ApproveValidator, approveValidator as defaultApproveValidator } from './policy/ApproveValidator';

const FRESHNESS_MS = 90_000;
const FLARE_MAINNET = 14;

interface EvaluateOpts {
  readonly userId: string;
  readonly now?: Date;
  /** When the intent was generated by an automation rule, pass its id so P9-cooldown applies. */
  readonly ruleId?: string;
  readonly ruleCooldownMinutes?: number;
  /** P15: provider health snapshot. If `down|disabled`, intent is blocked. */
  readonly providerHealth?: 'healthy' | 'degraded' | 'down' | 'disabled';
  /** P16: trust level of the price oracle backing the simulation. */
  readonly priceTrustLevel?:
    | 'onchain_verified'
    | 'oracle_verified'
    | 'protocol_native'
    | 'indexer_verified'
    | 'aggregator'
    | 'community'
    | 'unverified';
  /** P17: result of `prisma.wallet.findFirst({ address, userId })`; truthy = wallet registered to user. */
  readonly walletRegisteredToUser?: boolean;
  /** P18: SIWE session id resolved by middleware; absent or expired → block. */
  readonly sessionId?: string;
  readonly sessionValid?: boolean;
  /** P11: opt-in to allow unbounded ERC-20 approve. Default false. */
  readonly optInUnboundedApproval?: boolean;

  // ── P19–P30 (Control Plane hardening) ────────────────────────────────────

  /** P19: true when user is transacting with this protocol for the first time. */
  readonly isFirstProtocolUse?: boolean;
  /** P20: true when intent involves an asset the user has never transacted with. */
  readonly isFirstAssetUse?: boolean;
  /**
   * P21 / P24: true when the EXECUTION intent crosses chain boundaries (bridge / Squid / Axelar).
   * This flag is for EXECUTION policy only — it must never be set on read/discovery operations.
   * Cross-chain VISIBILITY (discovering positions on Ethereum, Polygon, Base…) is always allowed.
   * Cross-chain EXECUTION is disabled until V2.
   */
  readonly isBridgeAction?: boolean;
  /** P22: total USD value already executed today for this user (caller must aggregate). */
  readonly dailyValueUsedUSD?: number;
  /** P23: total USD value already executed this calendar month for this user. */
  readonly monthlyValueUsedUSD?: number;
  /** P25: confidence level of the position data backing this intent. 'unknown' blocks. */
  readonly positionConfidenceLevel?: 'verified' | 'probable' | 'detected' | 'unknown';
  /** P26: whether DEFIBRO_FEE_WALLET is configured (required for swap actions). */
  readonly feeWalletConfigured?: boolean;
  /** P27: if a partner session set defibroExecutes=true, block — Astryum never auto-executes. */
  readonly partnerDefibroExecutes?: boolean;
  /** P28–P29: origin of the intent. 'unknown' emits a warning; 'ai_copilot' requires user confirmation. */
  readonly intentSource?: 'user' | 'automation' | 'ai_copilot' | 'partner' | 'unknown';
  /** P28: AI-sourced intents must have explicit user confirmation before they can be signed. */
  readonly aiIntentUserConfirmed?: boolean;
  /** P30: per-tx USD cap for automation-generated intents (defaults to 50 % of mandate maxTxValueUSD). */
  readonly automationValueCapUSD?: number;

  // ── V2 P31–P35 (IntentPayload layer) ────────────────────────────────────

  /** P31: slippage in basis points from IntentPayload (must be ≤ mandate.limits.maxSlippageBps). */
  readonly slippageBps?: number;
  /** P32: must be literally true — referral must always be disclosed to user before authorization. */
  readonly referralDisclosedToUser?: boolean;
  /** P33: true when the action embeds referral and fee wallet must be configured. */
  readonly requiresFeeWallet?: boolean;
  /** P34: IntentPayload.tx.chainId — must match intent.action.targetChain. */
  readonly txPayloadChainId?: number;
  /** P35: IntentPayload.tx.to — must be in allowlist. */
  readonly txPayloadTo?: string;

  // ── V1.2 P38 (Identity / Compliance) ────────────────────────────────────

  /**
   * P38: Whether the caller confirmed the user is KYC-verified (kycVerified === true in DB).
   * Required when the intent targets a regulated partner (MoonPay Trade, Crossmint, AML actions).
   * The caller must look up User.kycVerified and pass it here — the guard never reads the DB.
   */
  readonly kycVerified?: boolean;

  // ── P-DELEGATION P_MANDATE (Manager-scoped guard) ────────────────────────

  /**
   * P_MANDATE: When a manager prepares an intent ON BEHALF of a user, the caller
   * must supply the active DelegationMandate. The guard checks:
   *   - mandate.status === 'active'
   *   - The protocol slug from intent.action is in mandate.allowedProtocols
   *   - The intent amount (USD) does not exceed mandate.maxCapitalUSD
   * Failure → 422 MANDATE_EXCEEDED. Must be evaluated BEFORE the intent is
   * returned to the manager. If this field is absent the check is skipped
   * (the intent is assumed to be user-originated).
   */
  readonly managerMandate?: {
    readonly mandateId: string;
    readonly managerId: string;
    readonly allowedProtocols: string[];
    readonly maxCapitalUSD: number;
    readonly status: string;
  };
  /** P_MANDATE: protocol slug the manager intends to act on (e.g. 'aave-v3'). */
  readonly managerIntentProtocol?: string;
  /** P_MANDATE: USD value of the manager-prepared action. */
  readonly managerIntentValueUSD?: number;
}

interface MutableCheck {
  passed: boolean;
  chainAllowed: boolean;
  walletAllowed: boolean;
  contractAllowed: boolean;
  actionAllowed: boolean;
  assetAllowed: boolean;
  valueWithinLimit: boolean;
  slippageWithinLimit: boolean;
  riskWithinLimit: boolean;
  dataFresh: boolean;
  providerHealthy: boolean;
  trustLevelSufficient: boolean;
  selectorMatchesAction: boolean;
  approveBoundedOrOptIn: boolean;
  intentNotExpired: boolean;
  sessionValid: boolean;
  warnings: string[];
  errors: { code: string; message: string }[];
  manualApprovalRequired: boolean;
  kycRequired: boolean;
  blocked: boolean;
  blockReason?: string;
  evaluatedAt: string;
  mandateId?: string;
}

/**
 * Deterministic security gate. Every action — user-driven, automation-driven,
 * or AI-suggested — passes through `evaluate(intent, ctx)` before being marked
 * `ready_to_sign`. No LLMs. No opinions. Either pass or block with a code.
 *
 * V1.1 implements rules P3–P14 deterministically. Rules tied to runtime state
 * we don't yet have wired (P15 provider health propagation, P17 wallet
 * registration check, P18 SIWE session) are evaluated when the data is passed
 * in by the caller; otherwise they default to permissive (`true`) and surface
 * a warning so they can be tightened later without breaking the contract.
 *
 * Spec: docs/POLICY_GUARD.md §2 / §4.
 */
export class PolicyGuard {
  constructor(
    private readonly mandates: MandateService = defaultMandates,
    private readonly allowlist: AllowlistService = defaultAllowlist,
    private readonly cooldowns: CooldownService = defaultCooldown,
    private readonly approves: ApproveValidator = defaultApproveValidator,
  ) {}

  evaluate(intent: PolicyEvaluable, opts: EvaluateOpts): PolicyCheck {
    const now = opts.now ?? new Date();
    const mandate = this.mandates.getActive(opts.userId);

    const c: MutableCheck = {
      passed: false,
      chainAllowed: true,
      walletAllowed: true,
      contractAllowed: true,
      actionAllowed: true,
      assetAllowed: true,
      valueWithinLimit: true,
      slippageWithinLimit: true,
      riskWithinLimit: true,
      dataFresh: true,
      providerHealthy: true,
      trustLevelSufficient: true,
      selectorMatchesAction: true,
      approveBoundedOrOptIn: true,
      intentNotExpired: true,
      sessionValid: true,
      warnings: [],
      errors: [],
      manualApprovalRequired: false,
      kycRequired: false,
      blocked: false,
      evaluatedAt: now.toISOString(),
      mandateId: mandate.id,
    };

    if (this.mandates.isExpired(mandate, now)) {
      block(c, 'mandate_expired', 'Mandate has expired — re-issue mandate before transacting.');
    }

    // P5 — chainId
    if (intent.action.targetChain !== FLARE_MAINNET) {
      c.chainAllowed = false;
      block(c, 'chain_not_allowed', `chainId ${intent.action.targetChain} not in V1.1 (Flare 14 only).`);
    }
    if (intent.txData && intent.txData.chainId !== FLARE_MAINNET) {
      c.chainAllowed = false;
      block(c, 'chain_not_allowed', `txData.chainId ${intent.txData.chainId} != 14`);
    }
    if (!mandate.scope.allowedChains.includes(intent.action.targetChain)) {
      c.chainAllowed = false;
      block(c, 'chain_not_in_mandate', `chain ${intent.action.targetChain} not in mandate.allowedChains`);
    }

    // P8 — action allowed by mandate
    if (mandate.scope.forbiddenActions.includes(intent.action.type)) {
      c.actionAllowed = false;
      block(c, 'action_forbidden', `action ${intent.action.type} is in mandate.forbiddenActions`);
    } else if (!mandate.scope.allowedActions.includes(intent.action.type)) {
      c.actionAllowed = false;
      block(c, 'action_not_allowed', `action ${intent.action.type} not in mandate.allowedActions`);
    }

    // Protocol scope
    if (!mandate.scope.allowedProtocols.includes(intent.action.targetProtocol)) {
      c.contractAllowed = false;
      block(
        c,
        'protocol_not_in_mandate',
        `protocol ${intent.action.targetProtocol} not in mandate.allowedProtocols`,
      );
    }

    // P6 — contract allowlist (only if txData present)
    if (intent.txData) {
      const allowed = this.allowlist.isAllowed(
        intent.action.targetProtocol,
        intent.txData.to,
        intent.action.type,
      );
      if (!allowed) {
        c.contractAllowed = false;
        block(
          c,
          'contract_not_allowed',
          `txData.to ${intent.txData.to} not allowlisted for ${intent.action.targetProtocol}/${intent.action.type}`,
        );
      }

      // P7 — selector matching
      if (
        !SelectorRegistry.matches(
          intent.action.targetProtocol,
          intent.action.type,
          intent.txData.data,
        )
      ) {
        c.selectorMatchesAction = false;
        block(
          c,
          'selector_mismatch',
          `calldata selector ${intent.txData.data.slice(0, 10)} does not match ${intent.action.targetProtocol}:${intent.action.type}`,
        );
      }
    } else {
      c.warnings.push('no_txdata_present_skipping_contract_and_selector_checks');
    }

    // P3 — simulation present
    if (!intent.simulationId) {
      c.dataFresh = false;
      block(c, 'simulation_missing', 'intent.simulationId is required before signing');
    }

    // P4 — simulation freshness
    if (intent.simulatedAt) {
      const age = now.getTime() - new Date(intent.simulatedAt).getTime();
      if (age > FRESHNESS_MS) {
        c.dataFresh = false;
        block(c, 'simulation_stale', `simulation is ${Math.floor(age / 1000)}s old (>90s) — re-simulate`);
      }
    }

    // P14 — price freshness
    if (intent.pricesFreshAt) {
      const age = now.getTime() - new Date(intent.pricesFreshAt).getTime();
      if (age > FRESHNESS_MS) {
        c.dataFresh = false;
        block(c, 'prices_stale', `prices are ${Math.floor(age / 1000)}s old (>90s) — refresh FTSO`);
      }
    }

    // P12 — intent expiry
    if (intent.expiresAt && new Date(intent.expiresAt).getTime() < now.getTime()) {
      c.intentNotExpired = false;
      block(c, 'intent_expired', 'intent has expired — recreate');
    }

    // P9 — value caps
    if (typeof intent.valueUSD === 'number' && intent.valueUSD > mandate.limits.maxTxValueUSD) {
      c.valueWithinLimit = false;
      block(
        c,
        'value_above_max_tx',
        `valueUSD ${intent.valueUSD} > mandate.maxTxValueUSD ${mandate.limits.maxTxValueUSD}`,
      );
    }

    // P10 — slippage caps
    if (typeof intent.slippageBps === 'number' && intent.slippageBps > mandate.limits.maxSlippageBps) {
      c.slippageWithinLimit = false;
      block(
        c,
        'slippage_above_max',
        `slippageBps ${intent.slippageBps} > mandate.maxSlippageBps ${mandate.limits.maxSlippageBps}`,
      );
    }

    // P13 — post-action HF / risk score under mandate floor
    if (
      intent.riskAfter &&
      typeof intent.riskAfter.healthFactor === 'number' &&
      typeof mandate.limits.minHealthFactorAfter === 'number' &&
      intent.riskAfter.healthFactor < mandate.limits.minHealthFactorAfter
    ) {
      c.riskWithinLimit = false;
      block(
        c,
        'hf_below_mandate_minimum',
        `post-action HF ${intent.riskAfter.healthFactor} < mandate.minHealthFactorAfter ${mandate.limits.minHealthFactorAfter}`,
      );
    }
    if (
      intent.riskAfter &&
      typeof intent.riskAfter.score === 'number' &&
      typeof mandate.limits.maxRiskScoreAfter === 'number' &&
      intent.riskAfter.score > mandate.limits.maxRiskScoreAfter
    ) {
      c.riskWithinLimit = false;
      block(
        c,
        'risk_score_above_mandate_max',
        `post-action risk score ${intent.riskAfter.score} > mandate.maxRiskScoreAfter ${mandate.limits.maxRiskScoreAfter}`,
      );
    }

    // Asset scope (best-effort: only when intent declares assets)
    if (intent.assets && intent.assets.length > 0) {
      const allowed = mandate.scope.allowedAssets.map((a) => a.toLowerCase());
      const offending = intent.assets.find((a) => !allowed.includes(a.toLowerCase()));
      if (offending) {
        c.assetAllowed = false;
        block(c, 'asset_not_in_mandate', `asset ${offending} not in mandate.allowedAssets`);
      }
    }

    // P9b — Rule cooldown (only applies when intent was generated by a rule)
    if (opts.ruleId) {
      const minutes = opts.ruleCooldownMinutes ?? mandate.limits.cooldownMinutesPerRule ?? 0;
      const status = this.cooldowns.status(opts.ruleId, minutes, now);
      if (status.active) {
        block(
          c,
          'cooldown_active',
          `rule ${opts.ruleId} is in cooldown (${status.remainingSeconds}s remaining)`,
        );
      }
    }

    // P11 — approve bounded unless explicit opt-in
    if (intent.txData) {
      const ar = this.approves.validate(intent, {
        optInUnboundedApproval: opts.optInUnboundedApproval,
      });
      if (ar.applies && !ar.bounded) {
        c.approveBoundedOrOptIn = false;
        block(c, 'approve_unbounded', ar.reason ?? 'unbounded approve not opted in');
      }
    }

    // P15 — provider health
    if (opts.providerHealth) {
      if (opts.providerHealth === 'down' || opts.providerHealth === 'disabled') {
        c.providerHealthy = false;
        block(c, 'provider_unhealthy', `provider health=${opts.providerHealth}`);
      } else if (opts.providerHealth === 'degraded') {
        c.warnings.push('provider_health_degraded');
      }
    }

    // P16 — price oracle trust level
    if (opts.priceTrustLevel) {
      const ok =
        opts.priceTrustLevel === 'oracle_verified' ||
        opts.priceTrustLevel === 'onchain_verified';
      if (!ok) {
        c.trustLevelSufficient = false;
        block(
          c,
          'price_trust_insufficient',
          `price trustLevel=${opts.priceTrustLevel} not in {oracle_verified, onchain_verified}`,
        );
      }
    }

    // P17 — wallet registered to user
    if (opts.walletRegisteredToUser === false) {
      c.walletAllowed = false;
      block(c, 'wallet_not_registered', 'wallet is not registered to authenticated user');
    }

    // P18 — SIWE session
    if (opts.sessionId !== undefined || opts.sessionValid !== undefined) {
      const valid = opts.sessionValid !== false && Boolean(opts.sessionId);
      if (!valid) {
        c.sessionValid = false;
        block(c, 'session_invalid', 'SIWE session missing or expired');
      }
    }

    // Manual-approval threshold (warning only, not a block)
    if (
      typeof intent.valueUSD === 'number' &&
      intent.valueUSD > mandate.approvals.requireManualApprovalAboveUSD
    ) {
      c.manualApprovalRequired = true;
      c.warnings.push(
        `manual_approval_required_above_${mandate.approvals.requireManualApprovalAboveUSD}_usd`,
      );
    }

    // ── P19–P30: Control Plane hardening ─────────────────────────────────

    // P19 — first use of a new protocol requires manual approval
    if (opts.isFirstProtocolUse && mandate.approvals.requireManualApprovalForNewProtocol) {
      c.manualApprovalRequired = true;
      c.warnings.push('new_protocol_requires_manual_approval');
    }

    // P20 — first use of a new asset requires manual approval
    if (opts.isFirstAssetUse && mandate.approvals.requireManualApprovalForNewAsset) {
      c.manualApprovalRequired = true;
      c.warnings.push('new_asset_requires_manual_approval');
    }

    // P21 — bridge actions require manual approval (and are disabled in V1.1 — P24)
    if (opts.isBridgeAction && mandate.approvals.requireManualApprovalForBridge) {
      c.manualApprovalRequired = true;
      c.warnings.push('bridge_action_requires_manual_approval');
    }

    // P22 — daily value cap
    if (typeof opts.dailyValueUsedUSD === 'number' && typeof intent.valueUSD === 'number') {
      const projectedDaily = opts.dailyValueUsedUSD + intent.valueUSD;
      if (projectedDaily > mandate.limits.maxDailyValueUSD) {
        c.valueWithinLimit = false;
        block(
          c,
          'daily_value_cap_exceeded',
          `projected daily total $${projectedDaily.toFixed(2)} exceeds mandate.maxDailyValueUSD $${mandate.limits.maxDailyValueUSD}`,
        );
      }
    }

    // P23 — monthly value cap
    if (typeof opts.monthlyValueUsedUSD === 'number' && typeof intent.valueUSD === 'number') {
      const projectedMonthly = opts.monthlyValueUsedUSD + intent.valueUSD;
      if (projectedMonthly > mandate.limits.maxMonthlyValueUSD) {
        c.valueWithinLimit = false;
        block(
          c,
          'monthly_value_cap_exceeded',
          `projected monthly total $${projectedMonthly.toFixed(2)} exceeds mandate.maxMonthlyValueUSD $${mandate.limits.maxMonthlyValueUSD}`,
        );
      }
    }

    // P24 — cross-chain EXECUTION disabled in V1.1
    // NOTE: This blocks bridge/cross-chain EXECUTION ONLY.
    // Cross-chain VISIBILITY (wallet discovery, position aggregation across Ethereum/Polygon/Base/etc.)
    // is NEVER blocked — observability is always-on and is the core value of the Control Plane.
    // isBridgeAction must only ever be true for execution intents, never for read operations.
    if (opts.isBridgeAction) {
      c.chainAllowed = false;
      block(c, 'cross_chain_disabled_v1', 'bridge and cross-chain EXECUTION disabled in V1.1 — cross-chain visibility is always enabled; multichain execution in V2');
    }

    // P25 — position confidence must not be unknown
    if (opts.positionConfidenceLevel === 'unknown') {
      c.dataFresh = false;
      block(
        c,
        'position_confidence_unknown',
        'intent is based on a position with unknown confidence — re-run discovery before acting',
      );
    }

    // P26 — swap actions require fee wallet to be configured
    if (intent.action.type === 'swap' && opts.feeWalletConfigured === false) {
      block(
        c,
        'swap_fee_wallet_not_configured',
        'DEFIBRO_FEE_WALLET env var not set — swap blocked until fee wallet is configured',
      );
    }

    // P27 — partner session defibroExecutes must always be false
    if (opts.partnerDefibroExecutes === true) {
      block(
        c,
        'partner_auto_execute_forbidden',
        'defibroExecutes must always be false — the user must confirm execution inside the partner UI; Astryum never executes on the user\'s behalf',
      );
    }

    // P28 — AI-sourced intents require explicit user confirmation
    if (opts.intentSource === 'ai_copilot' && opts.aiIntentUserConfirmed === false) {
      block(
        c,
        'ai_intent_unconfirmed',
        'intent sourced from AI Copilot requires explicit user confirmation before it can be signed',
      );
    }

    // P29 — unknown intent source emits a warning (not a block)
    if (!opts.intentSource || opts.intentSource === 'unknown') {
      c.warnings.push('intent_source_unknown_audit_trail_incomplete');
    }

    // P30 — automation-sourced intents are subject to a stricter per-tx value cap
    if (opts.intentSource === 'automation' && typeof intent.valueUSD === 'number') {
      const automationCap =
        opts.automationValueCapUSD ?? mandate.limits.maxTxValueUSD * 0.5;
      if (intent.valueUSD > automationCap) {
        c.valueWithinLimit = false;
        block(
          c,
          'automation_value_cap_exceeded',
          `automation intent valueUSD $${intent.valueUSD} exceeds automation cap $${automationCap.toFixed(2)} (50 % of mandate max or explicit cap)`,
        );
      }
    }

    // ── V2 P31–P35 (IntentPayload layer) ────────────────────────────────────

    // P31 — slippage must not exceed mandate.limits.maxSlippageBps (V2 swap intents)
    if (typeof opts.slippageBps === 'number') {
      const maxSlippage = mandate.limits.maxSlippageBps ?? 300; // default 3%
      if (opts.slippageBps > maxSlippage) {
        c.slippageWithinLimit = false;
        block(
          c,
          'slippage_exceeds_mandate',
          `slippageBps ${opts.slippageBps} exceeds mandate limit ${maxSlippage}`,
        );
      }
    }

    // P32 — referralAttribution.disclosedToUser must be literally true (no silent fee extraction)
    if (opts.referralDisclosedToUser === false) {
      block(
        c,
        'referral_not_disclosed',
        'referralAttribution.disclosedToUser must be true — Astryum never embeds fees without user visibility',
      );
    }

    // P33 — DEFIBRO_FEE_WALLET must be configured for any swap/stake/supply that embeds referral
    if (opts.requiresFeeWallet && !opts.feeWalletConfigured) {
      block(
        c,
        'fee_wallet_not_configured',
        'DEFIBRO_FEE_WALLET env var not set — cannot embed referral attribution in calldata',
      );
    }

    // P34 — tx.chainId in IntentPayload must match action.targetChain
    if (opts.txPayloadChainId !== undefined && opts.txPayloadChainId !== intent.action.targetChain) {
      c.chainAllowed = false;
      block(
        c,
        'payload_chain_mismatch',
        `IntentPayload.tx.chainId (${opts.txPayloadChainId}) != action.targetChain (${intent.action.targetChain})`,
      );
    }

    // P35 — tx.to must be in allowlist across any protocol
    // Uses hasContract scan (no action filter) since IntentPayload destination
    // should be verified regardless of which specific protocol owns it.
    if (opts.txPayloadTo) {
      // Check if address is known in any allowlisted protocol
      const p35Known = this.allowlist.knownAddress(opts.txPayloadTo);
      if (!p35Known) {
        c.contractAllowed = false;
        block(
          c,
          'payload_contract_not_allowlisted',
          `IntentPayload.tx.to ${opts.txPayloadTo} is not in the allowlist`,
        );
      }
    }

    // ── V1.2 P38: KYC verification required for regulated partner actions ────
    // Applies when the intent targets MoonPay Trade, Crossmint, or any partner
    // with AML obligations. The caller signals intent.requiresKyc=true and must
    // pass opts.kycVerified from User.kycVerified in DB. The guard never reads
    // the DB — separation of concerns.
    if (intent.requiresKyc || opts.kycVerified !== undefined) {
      if (intent.requiresKyc) {
        c.kycRequired = true;
        if (opts.kycVerified !== true) {
          block(
            c,
            'kyc_verification_required',
            'This action requires KYC identity verification — complete verification at /api/kyc/initiate',
          );
        }
      }
    }

    // ── P_MANDATE: Manager-scoped delegation guard ────────────────────────────
    // When a manager prepares an intent on behalf of a user, the caller must
    // supply opts.managerMandate. This check is skipped for user-originated
    // intents (opts.managerMandate absent).
    if (opts.managerMandate) {
      const m = opts.managerMandate;

      // Mandate must be active
      if (m.status !== 'active') {
        block(
          c,
          'MANDATE_EXCEEDED',
          `DelegationMandate ${m.mandateId} is not active (status=${m.status}) — the user must grant a new mandate`,
        );
      }

      // Protocol must be within mandate scope
      if (opts.managerIntentProtocol) {
        const protocolAllowed = m.allowedProtocols.includes(opts.managerIntentProtocol);
        if (!protocolAllowed) {
          c.contractAllowed = false;
          block(
            c,
            'MANDATE_EXCEEDED',
            `Protocol '${opts.managerIntentProtocol}' is not in the DelegationMandate allowedProtocols [${m.allowedProtocols.join(', ')}]`,
          );
        }
      }

      // Intent value must not exceed mandate capital cap
      if (typeof opts.managerIntentValueUSD === 'number') {
        if (opts.managerIntentValueUSD > m.maxCapitalUSD) {
          c.valueWithinLimit = false;
          block(
            c,
            'MANDATE_EXCEEDED',
            `Intent value $${opts.managerIntentValueUSD.toFixed(2)} exceeds DelegationMandate.maxCapitalUSD $${m.maxCapitalUSD.toFixed(2)}`,
          );
        }
      }
    }

    c.passed = !c.blocked;
    return c as PolicyCheck;
  }

  /** Convenience: returns true iff evaluate(...) passes. */
  permits(intent: PolicyEvaluable, opts: EvaluateOpts): boolean {
    return this.evaluate(intent, opts).passed;
  }
}

function block(c: MutableCheck, code: string, message: string): void {
  c.blocked = true;
  c.errors.push({ code, message });
  if (!c.blockReason) c.blockReason = code;
}

export const policyGuard = new PolicyGuard();
